/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPublic } from './UserPublic';
import {
    UserPublicFromJSON,
    UserPublicFromJSONTyped,
    UserPublicToJSON,
    UserPublicToJSONTyped,
} from './UserPublic';

/**
 * 
 * @export
 * @interface PostPublic
 */
export interface PostPublic {
    /**
     * 
     * @type {string}
     * @memberof PostPublic
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostPublic
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostPublic
     */
    published?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PostPublic
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof PostPublic
     */
    createdAt: Date;
    /**
     * 
     * @type {UserPublic}
     * @memberof PostPublic
     */
    owner: UserPublic;
    /**
     * 
     * @type {number}
     * @memberof PostPublic
     */
    averageRating: number;
}

/**
 * Check if a given object implements the PostPublic interface.
 */
export function instanceOfPostPublic(value: object): value is PostPublic {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('averageRating' in value) || value['averageRating'] === undefined) return false;
    return true;
}

export function PostPublicFromJSON(json: any): PostPublic {
    return PostPublicFromJSONTyped(json, false);
}

export function PostPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'published': json['published'] == null ? undefined : json['published'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'owner': UserPublicFromJSON(json['owner']),
        'averageRating': json['average_rating'],
    };
}

export function PostPublicToJSON(json: any): PostPublic {
    return PostPublicToJSONTyped(json, false);
}

export function PostPublicToJSONTyped(value?: PostPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'published': value['published'],
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'owner': UserPublicToJSON(value['owner']),
        'average_rating': value['averageRating'],
    };
}

