/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCreate
 */
export interface PostCreate {
    /**
     * 
     * @type {string}
     * @memberof PostCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreate
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostCreate
     */
    published?: boolean | null;
}

/**
 * Check if a given object implements the PostCreate interface.
 */
export function instanceOfPostCreate(value: object): value is PostCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function PostCreateFromJSON(json: any): PostCreate {
    return PostCreateFromJSONTyped(json, false);
}

export function PostCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'published': json['published'] == null ? undefined : json['published'],
    };
}

export function PostCreateToJSON(json: any): PostCreate {
    return PostCreateToJSONTyped(json, false);
}

export function PostCreateToJSONTyped(value?: PostCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'published': value['published'],
    };
}

